### ISSUE TITLE
Add tool to allow users to learn details of what variations are being tried upon them

### ISSUE THREAD

**Issue by jidanni** [brave/brave-variations#100]
One day the average chrome user sees
chrome://version/
and curious about the "variations" there,
finally reads that they are experiments.

In fact ones that make his browser behave different from his neighbors,
to the confusion of everybody.

So he researches how he might find out what experiments he is a guinea
pig for... but alas they are just coded strings of numbers and letters.

So later he reads that chrome://version/?show-variations-cmd can show
him more. But he still is treated like a wet food stamp -- no respect
for his right to know.

Therefore perhaps you folks could make a tool to help him list out
exactly what experiments he is subject to, in all detail.

Thanks.

**Comment by jidanni** [comment]
See also https://bugs.chromium.org/p/chromium/issues/detail?id=653634#c19 .

**Comment by iefremov** [comment]
@jidanni we already show variation names by default, please check brave://version (see also https://github.com/brave/brave-browser/issues/14780)

We also have a public dashboard https://griffin.brave.com/

and *some* of the experiments have human readable description on brave://flags/
Others can be easily found on our bugtracker.

**Comment by bsclifton** [comment]
Closing as question has been addressed and there hasn't been a response 😄

**Comment by jidanni** [comment]
(Erg, I am not brave enough to use brave,
and was thinking that maybe brave variations were the same as chrome variations,
and there might be a way to look the latter up. 
https://bugs.chromium.org/p/chromium/issues/detail?id=1246668#c16 )
