### ISSUE TITLE
Remove BraveTalk study

### ISSUE THREAD

**Issue by bsclifton** [brave/brave-variations#133]
It's rolled out live to users; ready to remove 😄 

~WIP `brave-core` branch here:~ UPDATE: merged
https://github.com/brave/brave-core/compare/bsc-remove-brave-talk-feature

For reference, flag added here:
https://github.com/brave/brave-core/pull/9605

Can't remove until this is merged and on release channel. Creating issue so I don't forget!

**Comment by bsclifton** [comment]
Created PR to remove this setting:
https://github.com/brave/brave-core/pull/10311

**Comment by bsclifton** [comment]
Setting can be removed once 1.32.x reaches master 😄

**Comment by iefremov** [comment]
@bsclifton just wanted to double-check that this is safe wrt to android. We wanted to remove the EphemeralStorage study, but turned out there is something like 15% of quite outdated clients on android that haven't received the proper binary yet (i.e. they rely on a feature flag enabled in griffin)

**Comment by bsclifton** [comment]
Oh yeah - this study not used on Android 😄 (only impacts desktop). Thanks for raising!
