### ISSUE TITLE
Roll out BraveBlockScreenFingerprinting to Desktop Release users

### ISSUE THREAD

**Issue by arthuredelstein** [brave/brave-variations#411]
Now we have rolled out to 100% of Nightly and Beta Desktop users, we are ready to roll out to Release. The plan is to do the following steps:
* [x] 10%
* [x] 25%
* [x] 50%
* [ ] 100%

After we get to 100%, and assuming there are no problems, we will enable the flag by default and we can remove from brave-variations.

**Comment by kjozwiak** [comment]
`BraveBlockScreenFingerprinting` was pushed to `production` at `10%` via https://github.com/brave/brave-variations/pull/413 on `Oct 27, 2022 @ 3:45am EST`.
