### ISSUE TITLE
Verify removal of `CookieListDefaultStudy` on `main`

### ISSUE THREAD

**Issue by antonok-edm** [brave/brave-variations#435]
`CookieListDefaultStudy` is being removed from `production` in #432. It's already not in `main` for some reason, but we'd like to double-check that everything works as expected on `main` before merging #432.

**Comment by kjozwiak** [comment]
QA has verified `BraveAdblockCookieListOptInReleaseStudy` pretty extensively while `CookieListDefaultStudy` was already removed from `main` as per the https://github.com/brave/brave-variations/pull/377#issuecomment-1259053975 & https://github.com/brave/brave-variations/pull/377#issuecomment-1259845225. Quickly went through a spot check and ensured that `BraveAdblockCookieListOptInReleaseStudy` was working as per the following:

Verification **PASSED** on `Win 11 x64` using the following build(s):

```
Brave | 1.45.118 Chromium: 107.0.5304.91 (Official Build) (64-bit)
-- | --
Revision | 3d5948960d62418160796d5831a4d2d7d6c90fa8-refs/branch-heads/5304@{#1097}
OS | Windows 11 Version 22H2 (Build 22621.755)
```

**`Example`** | **`Example`**
----------------|-----------------
![desktopRelease](https://user-images.githubusercontent.com/2602313/200239945-c1e17565-0049-4619-b628-5c84e0200d50.png) | ![image](https://user-images.githubusercontent.com/2602313/200239978-1034e689-86a3-4123-840b-0a74c1c83de0.png)

Verification **PASSED** on `Samsung Galaxy S10+` running `Android 12` using the following build(s):

```
Brave | 1.45.120 Chromium: 107.0.5304.91 (Official Build) (64-bit)
--- | ---
Revision | 3d5948960d62418160796d5831a4d2d7d6c90fa8-refs/branch-heads/5304@{#1097}
OS | Android 12; Build/SP1A.210812.016
```

**`Example`** | **`Example`** | **`Example`**
----------------|----------------|----------------
![Screenshot_20221107-013003_Brave](https://user-images.githubusercontent.com/2602313/200240946-1ba14bbf-7745-42c5-b28f-71306b473711.jpg) | ![Screenshot_20221107-013043_Brave](https://user-images.githubusercontent.com/2602313/200240965-9f4dbc37-3d6e-4231-920d-6556621089e3.jpg) | ![Screenshot_20221107-013025_Brave](https://user-images.githubusercontent.com/2602313/200240972-1e850b2d-e818-4739-8bd3-6d479c58c76f.jpg)
