### ISSUE TITLE
BraveAutoTranslateStudy for controlling auto-translate feature

### ISSUE THREAD

**Issue by atuchin-m** [brave/brave-variations#480]
b-c issue: https://github.com/brave/brave-browser/issues/27040
The feature should be gradually enabled for 100% users.

The first step: nightly/beta 100%

**Comment by kjozwiak** [comment]
Enabled on `Nightly` & `BETA` via https://github.com/brave/brave-variations/pull/481. QA verified the PR on `Nightly` & `BETA` via https://github.com/brave/brave-variations/pull/479#issuecomment-1340356174 & https://github.com/brave/brave-variations/pull/479#issuecomment-1340400758.

**Comment by kjozwiak** [comment]
Assuming the next step is to push the above on the `Release` channel starting at `100%`. CCing @rebron
