### ISSUE TITLE
Roll out Brave HTTPS by Default to Nightly Desktop

### ISSUE THREAD

**Issue by arthuredelstein** [brave/brave-variations#521]
We will start with 50% of Nightly Desktop users

**Comment by kjozwiak** [comment]
Closing as we've merged both https://github.com/brave/brave-variations/pull/522 & https://github.com/brave/brave-variations/pull/523 have been merged 👍 As discussed on Slack, the plan changed from rolling out at `50%` to `100%` so we can get more eyes on the feature quicker via Nightly and once `1.50.x` is migrated to `BETA` which includes https://github.com/brave/brave-browser/issues/27141.
