### ISSUE TITLE
Disable RendererAllocatesImages via Griffin

### ISSUE THREAD

**Issue by atuchin-m** [brave/brave-variations#951]
Chromium P1 issue: https://issues.chromium.org/issues/326802951
Brave Release 122 [is affected](https://sourcegraph.com/github.com/chromium/chromium@122.0.6261.94/-/blob/components/viz/common/features.cc?L236-238).

**Comment by kjozwiak** [comment]
Closing as the above was merged into `main` & `production` via https://github.com/brave/brave-variations/pull/952 & https://github.com/brave/brave-variations/pull/953.
